# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test if DMARC records are valid
#'
#' @param domains,dmarc_records character vectors of paired domains and DMARC records
#' @export
is_dmarc_valid <- function(domains, dmarc_records) {
    .Call('_dmarc_is_dmarc_valid', PACKAGE = 'dmarc', domains, dmarc_records)
}

#' Read DMARC records for a set of domains
#'
#' @param domains character vector of domain names
#' @export
read_dmarc <- function(domains) {
    .Call('_dmarc_read_dmarc', PACKAGE = 'dmarc', domains)
}

#' Parse already retrieved DMARC records
#'
#' @param domains,dmarc_records character vector of domain names and associated
#'        DMARC records.
#' @export
parse_dmarc <- function(domains, dmarc_records) {
    .Call('_dmarc_parse_dmarc', PACKAGE = 'dmarc', domains, dmarc_records)
}

