# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_report_from_file_int <- function(path) {
    .Call('_dmarc_parse_report_from_file_int', PACKAGE = 'dmarc', path)
}

#' Test if DMARC records are valid
#'
#' @param domains,dmarc_records character vectors of paired domains and DMARC records
#' @export
is_dmarc_valid <- function(domains, dmarc_records) {
    .Call('_dmarc_is_dmarc_valid', PACKAGE = 'dmarc', domains, dmarc_records)
}

int_read_dmarc <- function(domains) {
    .Call('_dmarc_int_read_dmarc', PACKAGE = 'dmarc', domains)
}

int_parse_dmarc <- function(domains, dmarc_records) {
    .Call('_dmarc_int_parse_dmarc', PACKAGE = 'dmarc', domains, dmarc_records)
}

